### ISSUE TITLE
Couldn't compile due to wrong type?

### ISSUE THREAD

**Issue by Lazarus9000** [daPhoosa/MedianFilter#2]
Hola,

Nice library, although I couldn't compile it (for reference, I am working on a ESP8266 project), not even the examples, due to wrong types?
Changed line 41 
MedianFilter(byte size, int seed);
to 
MedianFilter(int size, int seed);

and the corresponding lines in the .cpp file. Seemed to do the job.

**Comment by daPhoosa** [comment]
Try again with the latest changes (I don't have an ESP8266 to test on).  I now allow passing the window size as an int.

Phillip

**Comment by Lazarus9000** [comment]
Approved :)
